# Generated by Django 5.2.3 on 2025-07-03 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=14)),
                ('developers', models.ManyToManyField(related_name='sprints', to=settings.AUTH_USER_MODEL)),
                ('lead_developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sprints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
