# Generated by Django 5.2.3 on 2025-07-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('edit_user_profile_perm', 'Can edit user profile')]},
        ),
    ]
