# Generated by Django 5.2.3 on 2025-07-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='fixed_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
