# Generated by Django 5.2.3 on 2025-07-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_alter_bug_fixed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='fixed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
