# Generated by Django 5.2.3 on 2025-07-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_bug_in_progress_at_alter_bug_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='fixed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
